config/routes.rb
Rails.application.routes.draw do
  # root 'dashboard#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resources :notes
    resources :lessons do
      get :add_attachments
      member do
        delete :remove_attachment
      end
      resources :topics, only: [:new, :create, :destroy]
    end
    get 'schedule', to: 'schedules#index'
  end

  resources :conversations do
    resources :messages
  end

  resources :reports
  resources :students, only: [:index, :show, :new, :create, :edit, :update]
  resources :teachers, only: [:index, :show]

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show] do
        resources :lessons, only: [:show]
        resources :notes, only: [:create]
      end
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'landing', to: 'landing#index'
  root 'landing#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @today_lessons = @user.lessons.select do |lesson|
      lesson.occurrences.include?(Date.today.to_s)
    end.sort_by do |lesson|
      lesson.hour
    end

    @lessons = @user.lessons.map do |lesson|
      student = Student.find(lesson.student_id)
      teacher = Teacher.find(lesson.teacher_id)
      lesson.attributes.merge(student_name: student.name, teacher_name: teacher.name)
    end

    @notes = @user.notes.order(created_at: :desc)
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.slim
.dashboard
  .date-header
    h3.table-title
      = "Witaj #{current_user.name.split(' ')[0]}!"
    .date
      = Time.zone.now.strftime("%d.%m.%Y")
      .date-weekday
        = (I18n.t("date.day_names")[Date.today.day-1])&.upcase
  .dashboard-content
    .today-lessons
      .card-title
        .text
          = t(:today_lessons)
      - @today_lessons.each do |lesson|
        = link_to get_lesson_user_url(@user, lesson) do
          .lesson-block style="background-color: #{lesson.color.present? ? lesson.color : '' }; border-left: 3px solid #{darken_rgba_color(lesson.color)}"
            .hour
              = "#{lesson.hour.strftime("%H:%M")} - #{(lesson.hour + lesson.duration.minutes).strftime("%H:%M")}"
            .user
              .many-elements
                - if @user.is_a?(Teacher)
                  = image_tag url_for(lesson.student.avatar), class: "user-avatar-small" if lesson.student.avatar.present?
                  = lesson.student.name
                - if @user.is_a?(Student)
                  = image_tag url_for(lesson.teacher.avatar), class: "user-avatar-small" if lesson.teacher.avatar.present?
                  = lesson.teacher.name
      - unless @today_lessons.present?
        .no-data-info
          = t(:data_on_vacation)
          = fa_icon("paper-plane-o")
    .month-calendar-card
      .card-title
        .text
          = t(:month_calendar)
      .calendar data-controller="month-calendar"
        .month-schedule-navigation
          .month
            span data-month-calendar-target="currentMonth"
          .navigation
            .round-action-button data-action="click->month-calendar#prev"
              = fa_icon("angle-left")
            .round-action-button data-action="click->month-calendar#next"
              = fa_icon("angle-right")
        .schedule
          - resource = current_user.is_a?(Teacher) ? "T" : "S"
          #calendar data-lessons="#{@lessons.to_json}" data-resource="#{resource}"
    .user-notes
      .card-title
        .text
          .group
            = t(:my_notes)
            .add-note
              = link_to new_user_note_path(@user), data: {turbo_frame: "modal"} do
                = fa_icon("plus")
      = render 'dashboard/turbo/notes_turbo', notes: @notes
      