config/routes.rb
Rails.application.routes.draw do
  # root 'dashboard#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resources :notes
    resources :lessons do
      get :add_attachments
      member do
        delete :remove_attachment
      end
      resources :topics, only: [:new, :create, :destroy]
    end
    get 'schedule', to: 'schedules#index'
  end

  resources :conversations do
    resources :messages
  end

  resources :reports
  resources :students, only: [:index, :show, :new, :create, :edit, :update]
  resources :teachers, only: [:index, :show]

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show] do
        resources :lessons, only: [:show]
        resources :notes, only: [:create]
      end
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'landing', to: 'landing#index'
  root 'landing#index'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/api/v1/notes_controller.rb
class Api::V1::NotesController < ApiBaseController

  protect_from_forgery with: :null_session
  
  def create
    @user = User.find(params[:user_id])

    if @user.nil?
      render json: { error: 'User not found' }, status: :not_found
      return
    end

    @note = @user.notes.new(params[:note])

    if @note.save
      render json: @note, status: :created
    else
      render json: { errors: @note.errors.full_messages }, status: :unprocessable_entity
    end
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_user, only: %i[ new create edit update destroy ]

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = @user.notes.new(note_params)
    respond_to do |format|
      if @note.save
        @notes = @user.notes.order(created_at: :desc)
        flash[:notice] = flash_message(:create, Note)
        format.turbo_stream
        format.json { render :show, status: :created, location: @note }
        flash.discard
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        @notes = @user.notes.order(created_at: :desc)
        flash[:notice] = flash_message(:update, Note)
        format.turbo_stream
        format.json { render :show, status: :created, location: @note }
        flash.discard
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy!

    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: flash_message(:destroy, Note) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions
    def set_user
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content, :user_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.slim
= simple_form_for([@user.becomes(User), @note], html: { class: "modal-form" }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :content

  .form-actions
    = f.button :submit, class: "submit-button mt-2", data: { turbo: true }

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.replace 'user-notes-turbo', partial: 'dashboard/turbo/notes_turbo', locals: {notes: @notes} %>
<%= turbo_stream.replace 'flash_message', partial: 'application/flash' %>
<%= turbo_stream.replace 'modal', partial: 'shared/empty_modal' %>

app/views/notes/edit.html.slim
= turbo_frame_tag "modal" do
  .modal-overlay data-controller="modals" data-action="click->modals#closeByOverlay"
    .modal-form-card
      .modal-form-header
        h4.page-title.mb-0 = t(:edit_note)
        = link_to fa_icon('times'), "#", class: "close-link", data: { controller: "modals", action: "modals#close" }

      = render "form", user: @user, note: @note

app/views/notes/index.html.slim
p style="color: green" = notice

h1 Notes

#notes
  - @notes.each do |note|
    == render note
    p
      = link_to "Show this note", note

= link_to "New note", new_note_path

app/views/notes/new.html.slim
= turbo_frame_tag "modal" do
  .modal-overlay data-controller="modals" data-action="click->modals#closeByOverlay"
    .modal-form-card
      .modal-form-header
        h4.page-title.mb-0 = t(:add_note)
        = link_to fa_icon('times'), "#", class: "close-link", data: { controller: "modals", action: "modals#close" }

      = render "form", user: @user

app/views/notes/show.html.slim
p style="color: green" = notice

== render @note

div
  => link_to "Edit this note", edit_note_path(@note)
  '|
  =< link_to "Back to notes", notes_path

  = button_to "Destroy this note", @note, method: :delete

app/views/notes/update.turbo_stream.erb
<%= turbo_stream.replace 'user-notes-turbo', partial: 'dashboard/turbo/notes_turbo', locals: {notes: @notes} %>
<%= turbo_stream.replace 'flash_message', partial: 'application/flash' %>
<%= turbo_stream.replace 'modal', partial: 'shared/empty_modal' %>