config/routes.rb
Rails.application.routes.draw do
  # root 'dashboard#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resources :notes
    resources :lessons do
      get :add_attachments
      member do
        delete :remove_attachment
      end
      resources :topics, only: [:new, :create, :destroy]
    end
    get 'schedule', to: 'schedules#index'
  end

  resources :conversations do
    resources :messages
  end

  resources :reports
  resources :students, only: [:index, :show, :new, :create, :edit, :update]
  resources :teachers, only: [:index, :show]

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show] do
        resources :lessons, only: [:show]
        resources :notes, only: [:create]
      end
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'landing', to: 'landing#index'
  root 'landing#index'
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/views/landing/index.html.slim
.landing
  nav
    = image_tag asset_url("mentora_logo_inline.svg"), class: "logo"
    .nav-action
      = link_to t(:about), "#"
      = link_to t(:FAQ), "#"
      = link_to t(:contact), "#"
    .nav-login
      = link_to t(:join_us), dashboard_path, class: "nav-login-button"
  .motto-container
    .ball-container data-controller="landing"
    .motto
      .one
        | Porządek w 
        span.motto-color-one pracy
      .two
        | Efektywność w 
        span.motto-color-two nauce
      .description
        | Dzięki aplikacji, która zapewnia łatwą organizację zajęć pozaszkolnych 
        br
        | oraz łączy nauczycieli, uczniów i rodziców w jednym miejscu.
      .motto-action
        = link_to t(:do_it_together), dashboard_path, class: "motto-login-button"
      .more-button
        = link_to "#preview", class: "arrow" do
          = fa_icon("angle-down")

  .preview-container
    .preview-section#preview
      .preview-header
        .action-dot-red
        .action-dot-yellow
        .action-dot-green
      .splide[data-controller="splide"]
        .splide__track
          ul.splide__list
            li.splide__slide
              = image_tag asset_url("mentora_preview_1.png"), class: "preview_image"
            li.splide__slide
              = image_tag asset_url("mentora_preview_5.png"), class: "preview_image"
            li.splide__slide
              = image_tag asset_url("mentora_preview_2.png"), class: "preview_image"
            li.splide__slide
              = image_tag asset_url("mentora_preview_3.png"), class: "preview_image"
            li.splide__slide
              = image_tag asset_url("mentora_preview_7.png"), class: "preview_image"
            li.splide__slide
              = image_tag asset_url("mentora_preview_4.png"), class: "preview_image"
            li.splide__slide
              = image_tag asset_url("mentora_preview_6.png"), class: "preview_image"
            li.splide__slide
              = image_tag asset_url("mentora_preview_8.png"), class: "preview_image"
            li.splide__slide
              = image_tag asset_url("mentora_preview_9.png"), class: "preview_image"