config/routes.rb
Rails.application.routes.draw do
  # root 'dashboard#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resources :notes
    resources :lessons do
      get :add_attachments
      member do
        delete :remove_attachment
      end
      resources :topics, only: [:new, :create, :destroy]
    end
    get 'schedule', to: 'schedules#index'
  end

  resources :conversations do
    resources :messages
  end

  resources :reports
  resources :students, only: [:index, :show, :new, :create, :edit, :update]
  resources :teachers, only: [:index, :show]

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show] do
        resources :lessons, only: [:show]
        resources :notes, only: [:create]
      end
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'landing', to: 'landing#index'
  root 'landing#index'
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_week_days, only: %i[ index ]

  def index
    @lessons = @user.lessons.map do |lesson|
      student = Student.find(lesson.student_id)
      teacher = Teacher.find(lesson.teacher_id)
      lesson.attributes.merge(student_name: student.name, teacher_name: teacher.name)
    end
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_week_days
      @week_days = ["PON", "WTO", "ŚRO", "CZW", "PIĄ", "SOB", "NIE"]
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_calendar.html.slim
= turbo_frame_tag "lesson-calendar" do
  .calendar data-controller="calendar"
    .schedule-action
      h3.table-title
        = t(:calendar)
      .action-buttons
        = link_to new_user_lesson_path(@user), class: "main-button", title: t(:add_lesson), data: {turbo_frame: "modal"} do
          = t(:add_lesson)
          = fa_icon("plus-circle")
    .schedule-navigation
      .month
        span data-calendar-target="currentMonth"
      .navigation
        .round-action-button data-action="click->calendar#prev"
          = fa_icon("angle-left")
        .round-action-button data-action="click->calendar#next"
          = fa_icon("angle-right")
    .schedule
      #calendar data-lessons="#{lessons}"

app/views/schedules/_calendar_turbo.html.slim
= turbo_frame_tag "lesson-calendar" do
  .calendar data-controller="calendar"
    .schedule-action
      h3.table-title
        = t(:calendar)
      .action-buttons
        - if can?(:create, Lesson)
          = link_to new_user_lesson_path(@user), class: "main-button", title: t(:add_lesson), data: {turbo_frame: "modal"} do
            = t(:add_lesson)
            = fa_icon("plus-circle")
    .schedule-navigation
      .month
        span data-calendar-target="currentMonth"
      .navigation
        .round-action-button data-action="click->calendar#prev"
          = fa_icon("angle-left")
        .round-action-button data-action="click->calendar#next"
          = fa_icon("angle-right")
    .schedule
      - resource = current_user.is_a?(Teacher) ? "T" : "S"
      #calendar data-lessons="#{lessons}" data-resource="#{resource}"

app/views/schedules/index.html.slim
= render 'calendar_turbo', lessons: @lessons.to_json